baseURL = "/"
languageCode = "en-us"
title = "Dirty Lemon"
pluralizeListTitles = "false"

[menu] 
  [[menu.main-1]]
    name = "Illustration"
    url = "/illustration"
    weight = 1
  [[menu.main-1]]
    name = "Paper artwork"
    url = "/paper-artwork"
    weight = 2
  [[menu.main-1]]
    name = "Murals"
    url = "/murals"
    weight = 3 
  [[menu.main-1]]
    name = "Everything else"
    url = "/everything-else"
    weight = 4
  [[menu.main]]
    name = "Get in touch 👋"
    url = "/get-in-touch"
    weight = 5

[params]
  email = "hello@dirtylemon.studio"
  metadescription = "Dirty Lemon is a design studio specialising in fun & happy creative artwork!"

[related]
    treshold = 1
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "CurrentSection.Title"
        weight = 75
    [[related.indices]]
        name = "Section.Title"
        weight = 50
    [[related.indices]]
        name = "description"
        weight = 25