baseURL = "/"
languageCode = "en-us"
title = "Dirty Lemon"
pluralizeListTitles = "false"

[menu]
  [[menu.main]]
    name = "Get in touch 👋"
    url = "#get-in-touch"
    weight = 1

[params]
  email = "hello@dirtylemon.studio"
  metadescription = "Dirty Lemon is a design studio specialising in fun & happy creative artwork!"

[related]
    treshold = 1
    includeNewer = true
    toLower = false

    [[related.indices]]
        name = "CurrentSection.Title"
        weight = 75
    [[related.indices]]
        name = "Section.Title"
        weight = 50
    [[related.indices]]
        name = "description"
        weight = 25