[build]
  publish = "public"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  # If it should show more verbose logs (optional, default = true)
  debug = false

[[plugins]]
  package = "netlify-plugin-image-optim"

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/laura.snclr/"
  status = 301