[build]
  publish = "public"
  build = "hugo"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  # If it should show more verbose logs (optional, default = true)
  debug = false

[[plugins]]
  package = "netlify-plugin-image-optim"

[[redirects]]
  from = "/instagram"
  to = "https://instagram.com/laura.snclr/"
  status = 301

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/laurasnclr/"
  status = 301

[[redirects]]
  from = "/behance"
  to = "https://www.behance.net/laurasnclr/"
  status = 301

[[redirects]]
  from = "/work"
  to = "/#work"
  status = 301